XYBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    # ex: /blog/
    url(r'^$', views.index, name='index'),
    # ex: /blog/list/
    url(r'^list/$', views.list, name='list'),
    # ex: /blog/5/
    url(r'^detail/(?P<blog_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /blog/register/
    url(r'^register/$', views.register, name='register'),
    # ex: /blog/login/
    url(r'^login/$', views.login, name='login'),
    # ex: /blog/write/
    url(r'^write/$', views.write, name='write'),
    # ex: /blog/logout/
    url(r'^logout/$', views.logout, name='logout'),
]

blog/models.py
from __future__ import unicode_literals

from django.db import models

class User(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField()
    password = models.CharField(max_length=128)
#     image = models.ImageField(upload_to='blog/images/user_images', blank=True)
    create_time = models.DateTimeField(auto_now_add=True)
    
    def __unicode__(self):
        return self.name
    
class Blog(models.Model):
    title = models.CharField(max_length=80)
    summary = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='blog/images/blog_images', blank=True)
    create_time = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __unicode__(self):
        return self.title

blog/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import Http404
from django.contrib import messages

from .models import Blog, User
from .cookies import LOGIN_COOKIE, LOGIN_COOKIE_AGE
import cookies

def index(request):
    user = None
    blogs = None
    if hasattr(request, 'blog_user') and request.blog_user is not None:
        user = request.blog_user
        blogs = Blog.objects.filter(user_id=user.id).order_by('-create_time')
    else:
        blogs = Blog.objects.all().order_by('-create_time')
    context = {
        'user': user,
        'blogs': blogs,
    }
    return render(request, 'blog/index.html', context)

def list(request):
    user = None
    blogs = None
    login_cookie = None
    if request.method == 'GET':
        if LOGIN_COOKIE in request.COOKIES:
            login_cookie = request.COOKIES[LOGIN_COOKIE]
        if hasattr(request, 'blog_user') and request.blog_user is not None:
            user = request.blog_user
            blogs = Blog.objects.filter(user_id=user.id).order_by('-create_time')
        else:
            blogs = Blog.objects.all().order_by('-create_time')
    elif request.method == 'POST':
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        password = request.POST.get('password', '')
        if name == '':
            # 登录
            try:
                user = get_object_or_404(User, email=email)
            except Http404:
                messages.add_message(request, messages.WARNING, u'账户不存在！')
                return redirect(reverse('blog:login'))
            if password != user.password:
                messages.add_message(request, messages.WARNING, u'密码错误！')
                return redirect(reverse('blog:login'))
        else:
            # 注册
            try:
                user = get_object_or_404(User, email=email)
                messages.add_message(request, messages.WARNING, u'电子邮箱已被注册！')
                return redirect(reverse('blog:register'))
            except Http404:
                user = User(name=name, email=email, password=password)
                user.save()
        login_cookie = cookies.generate_login_cookie(user.id, user.password, LOGIN_COOKIE_AGE)
        blogs = Blog.objects.filter(user_id=user.id).order_by('-create_time')
    context = {
        'user': user,
        'blogs': blogs,
    }
    response = render(request, 'blog/list.html', context)
    if login_cookie is not None:
        response.set_cookie(LOGIN_COOKIE, login_cookie)
    return response

def detail(request, blog_id):
    user = None
    blog = None
    if hasattr(request, 'blog_user') and request.blog_user is not None:
        user = request.blog_user
    if int(blog_id) == 0:
        if request.method == 'POST':
            # 新建博客
            title = request.POST.get('title', 'No title')
            summary = request.POST.get('summary', 'No summary')
            content = request.POST.get('content', 'No content')
            if 'image' in request.FILES:
                blog = Blog(title=title, summary=summary, content=content, user=user, image=request.FILES['image'])
            else:
                blog = Blog(title=title, summary=summary, content=content, user=user)
            blog.save()
    else:
        # 显示已有博客
        blog = get_object_or_404(Blog, pk=blog_id)
        print type(blog.image)
        print blog.image
    context = {
        'user': user,
        'blog': blog,
    }
    return render(request, 'blog/detail.html', context)

def register(request):
    return render(request, 'blog/register.html')

def login(request):
    return render(request, 'blog/login.html')

def write(request):
    user = None
    if hasattr(request, 'blog_user') and request.blog_user is not None:
        user = request.blog_user
    context = {
        'user': user,
    }
    return render(request, 'blog/write.html', context)

def logout(request):
    response = redirect(reverse('blog:index'))
    if LOGIN_COOKIE in request.COOKIES:
        response.delete_cookie(LOGIN_COOKIE)
    return response

blog/templates/blog/__base__.html
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block meta %}{% endblock %}

	<title>{% block title %} ? {% endblock %} - XY博客</title>

	{% load static %}
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/xyblog-style.css' %}">
    <script type="text/javascript" src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'blog/js/jquery-1.11.3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'blog/js/tether.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'blog/js/md5.js' %}"></script>
    
    {% block beforehead %}{% endblock %}
</head>

<body>

	<div class="xy-header">
		<div class="container-fluid">
			<div class="xy-header-inner">
				<a href="{% url 'blog:index' %}" class="navbar-brand xy-site-name">XY博客</a>

				<nav class="navbar xy-main-nav">

					<button class="navbar-toggler hidden-md-up" type="button"
						data-toggle="collapse" data-target="#tmNavbar">&#9776;</button>

					<div class="collapse navbar-toggleable-sm" id="tmNavbar">
						<ul class="nav navbar-nav">
							{% block nav-li-index %}<li class="nav-item"><a href="{% url 'blog:index' %}" class="nav-link">首页</a></li>{% endblock %}
							{% block nav-li-list %}<li class="nav-item"><a href="{% url 'blog:list' %}" class="nav-link">看看</a></li>{% endblock %}
							{% block nav-li-write %}<li class="nav-item"><a href="{% url 'blog:write' %}" class="nav-link">写写</a></li>{% endblock %}
							{% block nav-li-login %}<li class="nav-item"><a href="{% url 'blog:login' %}" class="nav-link">登录</a></li>{% endblock %}
						</ul>
					</div>

				</nav>

			</div>
		</div>
	</div>

	{% block page_image %}
	{% endblock %}

	{% block main %}
	{% endblock %}

	<footer class="xy-footer">
		<div class="container-fluid">
			<div class="row">
				<div class="col-xs-12 xy-copyright-col">
					<p class="xy-copyright-text">
						Copyright 2016&nbsp;&nbsp;&nbsp;&nbsp;黄昊宇&nbsp;&nbsp; 联系方式：hy.huang@foxmail.com
					</p>
				</div>
			</div>
		</div>
	</footer>

</body>

</html>

blog/templates/blog/detail.html
{% extends "blog/__base__.html" %}

{% block title %}博客详情{% endblock %}

{% block nav-li-list %}
<li class="nav-item active"><a href="#" class="nav-link">看看</a></li>
{% endblock %}

{% block nav-li-login %}
{% if user %}
	<li class="nav-item" id="user-item"><a href="#" class="nav-link">{{ user.name }}</a></li>
	<li class="nav-item" id="logout-item" style="display: none;"><a href="{% url 'blog:logout' %}" class="nav-link">退出</a></li>
{% else %}
	<li class="nav-item"><a href="{% url 'blog:login' %}" class="nav-link">登录</a></li>
{% endif %}
{% endblock %}

{% block page_image %}
<div class="xy-blog-img-container"></div>
{% endblock %}

{% block beforehead %}
<script>
$(document).on('ready', function() {
	$('#user-item').on('mouseenter', function() {
		$(this).hide();
		$('#logout-item').show();
	});
	$('#logout-item').on('mouseleave', function() {
		$(this).hide();
		$('#user-item').show();
	});
});
</script>
{% endblock %}

{% block main %}
<section class="xy-section">
	<div class="container-fluid">
		<div class="row">

			<div class="col-xs-12 col-sm-12 col-md-8 col-lg-9 col-xl-9">
				<div class="xy-blog-post">
					<h3 class="xy-gold-text">{{ blog.title }}</h3>
					<p>{{ blog.summary }}</p>
					{% if blog.image %}
					<img src="{{ blog.image.url }}" alt="Image" class="img-fluid xy-img-post">
					{% endif %}
					<p>{{ blog.content }}</p>
				</div>
			</div>

			<aside class="col-xs-12 col-sm-12 col-md-4 col-lg-3 col-xl-3 xy-aside-r">
				<div class="xy-aside-container">
					
					<a href="{% url 'blog:write' %}" class="xy-btn text-uppercase" style="font-size: 1.65rem;">写博客</a>
					<hr class="xy-margin-t-small">
					
					<h3 class="xy-gold-text xy-title">可能想看</h3>
					<nav>
						<ul class="nav">
							<li><a href="#" class="xy-text-link">Lorem ipsum dolor sit</a></li>
							<li><a href="#" class="xy-text-link">Tincidunt non faucibus placerat</a></li>
							<li><a href="#" class="xy-text-link">Vestibulum tempor ac lectus</a></li>
							<li><a href="#" class="xy-text-link">Elementum egestas dui</a></li>
							<li><a href="#" class="xy-text-link">Nam in augue consectetur</a></li>
							<li><a href="#" class="xy-text-link">Fusce non turpis euismod</a></li>
							<li><a href="#" class="xy-text-link">Text Link Color #006699</a></li>
						</ul>
					</nav>
					<hr class="xy-margin-t-small">
					
				</div>
			</aside>

		</div>
	</div>
</section>
{% endblock %}

blog/templates/blog/index.html
{% extends "blog/__base__.html" %}

{% block title %}首页{% endblock %}

{% block nav-li-index %}
<li class="nav-item active"><a href="#" class="nav-link">首页</a></li>
{% endblock %}

{% block nav-li-login %}
{% if user %}
	<li class="nav-item" id="user-item"><a href="#" class="nav-link">{{ user.name }}</a></li>
	<li class="nav-item" id="logout-item" style="display: none;"><a href="{% url 'blog:logout' %}" class="nav-link">退出</a></li>
{% else %}
	<li class="nav-item"><a href="{% url 'blog:login' %}" class="nav-link">登录</a></li>
{% endif %}
{% endblock %}

{% block page_image %}
{% load static %}
<div class="xy-home-img-container">
	<img src="{% static 'blog/images/tm-home-img.jpg' %}" alt="Image" class="hidden-lg-up img-fluid">
</div>
{% endblock %}

{% block beforehead %}
<script>
$(document).on('ready', function() {
	$('#user-item').on('mouseenter', function() {
		$(this).hide();
		$('#logout-item').show();
	});
	$('#logout-item').on('mouseleave', function() {
		$(this).hide();
		$('#user-item').show();
	});
});
</script>

<style>
.img-box {
	float: left;
	position: relative;
	left: 50%;
}
.blog-image {
	height: 180px;
	max-width: initial;
    position: relative;
    right: 50%;
}
.blog-title {
	width: inherit;
	height: 35px;
	text-overflow: ellipsis;
	overflow: hidden;
	white-space: nowrap;
}
.blog-summary {
	width: inherit;
    height: 68px;
    text-overflow: ellipsis;
    overflow: hidden;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
}
</style>
{% endblock %}

{% block main %}
<section class="xy-section">
	<div class="container-fluid">
		<div class="row">
			{% for blog in blogs %} 
				{% if forloop.counter <= 4 and blog is not None %}
				<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 col-xl-3">
					<div class="xy-content-box">
						{% if blog.image %}
						<div class="img-box">
							<img src="{{ blog.image.url }}" alt="Image" class="xy-margin-b-20 img-fluid blog-image">
						</div>
						{% endif %}
						<div style="width: inherit; height: 180px; margin-bottom: 20px;"><!-- 占位的div元素 --></div>
						<h4 class="xy-margin-b-20 xy-gold-text blog-title">{{ blog.title }}</h4>
						<p class="xy-margin-b-20 blog-summary">{{ blog.summary }}</p>
						<a href="{% url 'blog:detail' blog.id %}" class="xy-btn text-uppercase">详情</a>
					</div>
				</div>
				{% endif %}
			{% empty %}
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
					<p>还没有人写过博客~</p>
				</div>
			{% endfor %}
		</div>
	</div>
</section>
{% endblock %}

blog/templates/blog/list.html
{% extends "blog/__base__.html" %}

{% block title %}博客列表{% endblock %}

{% block nav-li-list %}
<li class="nav-item active"><a href="#" class="nav-link">看看</a></li>
{% endblock %}

{% block nav-li-login %}
{% if user %}
	<li class="nav-item" id="user-item"><a href="#" class="nav-link">{{ user.name }}</a></li>
	<li class="nav-item" id="logout-item" style="display: none;"><a href="{% url 'blog:logout' %}" class="nav-link">退出</a></li>
{% else %}
	<li class="nav-item"><a href="{% url 'blog:login' %}" class="nav-link">登录</a></li>
{% endif %}
{% endblock %}

{% block page_image %}
<div class="xy-blog-img-container"></div>
{% endblock %}

{% block beforehead %}
<script>
$(document).on('ready', function() {
	$('#user-item').on('mouseenter', function() {
		$(this).hide();
		$('#logout-item').show();
	});
	$('#logout-item').on('mouseleave', function() {
		$(this).hide();
		$('#user-item').show();
	});
});
</script>

<style>
.blog-title {
	width: inherit;
	height: 2rem;
	text-overflow: ellipsis;
	overflow: hidden;
	white-space: nowrap;
}
.blog-summary {
	width: inherit;
	height: 2rem;
	text-overflow: ellipsis;
	overflow: hidden;
	white-space: nowrap;
}
.blog-content {
	width: inherit;
    height: 4rem;
    text-overflow: ellipsis;
    overflow: hidden;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
}
</style>
{% endblock %}

{% block main %}
<section class="xy-section">
	<div class="container-fluid">
		<div class="row">
		
			<div class="col-xs-12 col-sm-12 col-md-8 col-lg-9 col-xl-9">
				{% for blog in blogs %}
				<div class="xy-blog-post" style="margin-bottom: 4rem;">
					<h3><a href="{% url 'blog:detail' blog.id %}" class="xy-gold-text blog-title">{{ blog.title }}</a></h3>
					<p class="blog-summary">{{ blog.summary }}</p>
					{% if blog.image %}
					<img src="{{ blog.image.url }}" alt="Image" class="img-fluid xy-img-post">
					{% endif %}
					<p class="blog-content">{{ blog.content }}</p>
				</div>
				{% empty %}
				<p>还没有写过博客，<a href="{% url 'blog:write' %}" class="xy-text-link">快来写写吧>>></a></p>
				{% endfor %}
			</div>
			
			<aside class="col-xs-12 col-sm-12 col-md-4 col-lg-3 col-xl-3 xy-aside-r">
				<div class="xy-aside-container">
					
					<a href="{% url 'blog:write' %}" class="xy-btn text-uppercase" style="font-size: 1.65rem;">写博客</a>
					<hr class="xy-margin-t-small">
					
					<h3 class="xy-gold-text xy-title">可能想看</h3>
					<nav>
						<ul class="nav">
							<li><a href="#" class="xy-text-link">Lorem ipsum dolor sit</a></li>
							<li><a href="#" class="xy-text-link">Tincidunt non faucibus placerat</a></li>
							<li><a href="#" class="xy-text-link">Vestibulum tempor ac lectus</a></li>
							<li><a href="#" class="xy-text-link">Elementum egestas dui</a></li>
							<li><a href="#" class="xy-text-link">Nam in augue consectetur</a></li>
							<li><a href="#" class="xy-text-link">Fusce non turpis euismod</a></li>
							<li><a href="#" class="xy-text-link">Text Link Color #006699</a></li>
						</ul>
					</nav>
					<hr class="xy-margin-t-small">
					
				</div>
			</aside>
			
		</div>
	</div>
</section>
{% endblock %}

blog/templates/blog/login.html
{% extends "blog/__base__.html" %}

{% block title %}登录{% endblock %}

{% block nav-li-login-register %}
<li class="nav-item active"><a href="#" class="nav-link">登录</a></li>
{% endblock %}

{% block page_image %}
<div class="xy-contact-img-container"></div>
{% endblock %}

{% block beforehead %}
<script>
function check_form() {
	re = new RegExp("^[\\w!#$%&'*+/=?^_`{|}~-]+(?:\\.[\\w!#$%&'*+/=?^_`{|}~-]+)*@(?:[\\w](?:[\\w-]*[\\w])?\\.)+[\\w](?:[\\w-]*[\\w])?$");
	if (!re.test($('#email').val())) {
		var email_error = $('form #email-error');
		email_error.text('邮箱格式不正确！');
		email_error.show();
		return false;
	} // if
	$('#password').val(CryptoJS.MD5($('#password1').val()).toString());
	return true;
}
</script>

<style type="text/css">
.error-msg {
    color: red;
    font-size: .8rem;
    margin-top: -.5rem;
    margin-bottom: 1rem;
    display: none;
}
</style>
{% endblock %}

{% block main %}
<section class="xy-section">
	<div class="container-fluid">
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 col-lg-offset-3 col-xl-offset-3">
				<section>
					<h3 class="xy-gold-text xy-form-title">欢迎回来！</h3>
					{% if messages %}
					{% for message in messages %}
					<h5 style="color:red; font-size:.8rem; margin-top:1.2rem;">{{ message }}</h5>
					{% endfor %}
					{% endif %}
					<form action="{% url 'blog:list' %}" method="post" class="xy-contact-form" onsubmit="return check_form()">
						{% csrf_token %}
						<div class="form-group">
							<input type="text" id="email" name="email" class="form-control" placeholder="电子邮箱" required />
						</div>
						<h5 class="error-msg" id="email-error"></h5>
						<div class="form-group">
							<input type="password" id="password1" class="form-control" placeholder="密码" required />
							<input type="hidden" id="password" name="password" class="form-control" />
						</div>
						<button type="submit" class="xy-btn">登录</button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'blog:register' %}" class="xy-text-link">未有账户？点此注册>>></a>
					</form>
				</section>
			</div>
		</div>
	</div>
</section>
{% endblock %}

blog/templates/blog/register.html
{% extends "blog/__base__.html" %}

{% block title %}注册{% endblock %}

{% block nav-li-login-register %}
<li class="nav-item active"><a href="#" class="nav-link">注册</a></li>
{% endblock %}

{% block page_image %}
<div class="xy-contact-img-container"></div>
{% endblock %}

{% block beforehead %}
<script>
function check_form() {
	$('form #name-error').text('');
	$('form #email-error').text('');
	$('form #password-error').text('');
	// 检车用户名
	var re = new RegExp("^[\\u4e00-\\u9fa5a-zA-Z0-9_-]+$");
	if ($('#name').val().length > 20) {
		var name_error = $('form #name-error');
		name_error.text('用户名不能超过20个字符！');
		name_error.show();
		return false;
	} else if (!re.test(name_error)) {
		var name_error = $('form #name-error');
		name_error.text('用户名只能包含汉字、字母、下划线和连接符！');
		name_error.show();
		return false;
	} // if
	// 检查电子邮箱
	re = new RegExp("^[\\w!#$%&'*+/=?^_`{|}~-]+(?:\\.[\\w!#$%&'*+/=?^_`{|}~-]+)*@(?:[\\w](?:[\\w-]*[\\w])?\\.)+[\\w](?:[\\w-]*[\\w])?$");
	if (!re.test($('#email').val())) {
		var email_error = $('form #email-error');
		email_error.text('邮箱格式不正确！');
		email_error.show();
		return false;
	} // if
	// 检查密码
	re = new RegExp("^[^\\u4e00-\\u9fa5 ]+$");
	if ($('#password1').val().length > 20) {
		var password_error = $('form #password-error');
		password_error.text('密码长度不能超过20个字符！');
		password_error.show();
		return false;
	} else if (!re.test($('#password1').val())) {
		var password_error = $('form #password-error');
		password_error.text('密码不能包含汉字和空格！');
		password_error.show();
		return false;
	} else if ($('#password1').val() != $('#password2').val()) {
		var password_error = $('form #password-error');
		password_error.text('两次输入的密码不一致！');
		password_error.show();
		return false;
	} // if
	$('#password').val(CryptoJS.MD5($('#password1').val()).toString());
	return true;
}
</script>

<style type="text/css">
.error-msg {
    color: red;
    font-size: .8rem;
    margin-top: -.5rem;
    margin-bottom: 1rem;
    display: none;
}
</style>
{% endblock %}

{% block main %}
<section class="xy-section">
	<div class="container-fluid">
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 col-lg-offset-3 col-xl-offset-3">
				<section>
					<h3 class="xy-gold-text xy-form-title">欢迎注册！</h3>
					{% if messages %}
					{% for message in messages %}
					<h5 style="color:red; font-size:.8rem; margin-top:1.2rem;">{{ message }}</h5>
					{% endfor %}
					{% endif %}
					<form action="{% url 'blog:list' %}" method="post" class="xy-contact-form" onsubmit="return check_form()">
						{% csrf_token %}
						<div class="form-group">
							<input type="text" id="name" name="name" class="form-control" placeholder="用户名，不超过20个字符" required />
						</div>
						<h5 class="error-msg" id="name-error"></h5>
						<div class="form-group">
							<input type="text" id="email" name="email" class="form-control" placeholder="电子邮箱" required />
						</div>
						<h5 class="error-msg" id="email-error"></h5>
						<div class="form-group">
							<input type="password" id="password1" class="form-control" placeholder="密码，不超过20个字符" required />
							<input type="hidden" id="password" name="password" class="form-control" />
						</div>
						<div class="form-group">
							<input type="password" id="password2" class="form-control" placeholder="重复密码" required />
						</div>
						<h5 class="error-msg" id="password-error"></h5>
						<button type="submit" class="xy-btn">注册</button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'blog:login' %}" class="xy-text-link">已有账户？点此登录>>></a>
					</form>
				</section>
			</div>
		</div>
	</div>
</section>
{% endblock %}

blog/templates/blog/write.html
{% extends "blog/__base__.html" %}

{% block title %}写博客{% endblock %}

{% block nav-li-login %}
{% if user %}
	<li class="nav-item" id="user-item"><a href="#" class="nav-link">{{ user.name }}</a></li>
	<li class="nav-item" id="logout-item" style="display: none;"><a href="{% url 'blog:logout' %}" class="nav-link">退出</a></li>
{% else %}
	<li class="nav-item"><a href="{% url 'blog:login' %}" class="nav-link">登录</a></li>
{% endif %}
{% endblock %}

{% block beforehead %}
<script>
$(document).on('ready', function() {
	var uploadImage = $('form input#image');
	uploadImage.on('change', function() {
		var file = $(this).prop('files')[0];
		var splitFileName = file.name.split('.');
		var extension = splitFileName[splitFileName.length-1];
		if (extension.toLocaleLowerCase() != 'jpg' 
				&& extension.toLocaleLowerCase() != 'jpeg' 
				&& extension.toLocaleLowerCase() != 'png' 
				&& extension.toLocaleLowerCase() != 'bmp' 
				&& extension.toLocaleLowerCase() != 'gif') {
			$('#image-invalid').show();
			$('form img#preview-image').hide();
			return;
		} else {
			$('#image-invalid').hide();
		} // if
		var reader = new FileReader();
		reader.onload = function (e) {
			$('form img#preview-image').attr('src', e.target.result);
		}
		reader.readAsDataURL(file);
		$('form img#preview-image').show();
	});
	$('#user-item').on('mouseenter', function() {
		$(this).hide();
		$('#logout-item').show();
	});
	$('#logout-item').on('mouseleave', function() {
		$(this).hide();
		$('#user-item').show();
	});
});
</script>

<style>
#image-invalid {
	color: red;
    font-size: .8rem;
    margin-top: -.5rem;
    margin-bottom: 1rem;
    display: none;
}
form img#preview-image {
	display: none;
	height: 180px;
	width: auto;
}
</style>
{% endblock %}

{% block nav-li-write %}
<li class="nav-item active"><a href="#" class="nav-link">写写</a></li>
{% endblock %}

{% block page_image %}
<div class="xy-about-img-container"></div>
{% endblock %}

{% block main %}
{% if user %}
<section class="xy-section">
	<div class="container-fluid">
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
				<section>
					<form action="{% url 'blog:detail' 0 %}" method="post" enctype="multipart/form-data" class="xy-contact-form">
						{% csrf_token %}
						<div class="form-group">
							<label for="title">标题</label>
							<input type="text" class="form-control" id="title" name="title" required />
						</div>
						<div class="form-group">
							<label for="summary">概要</label>
							<input type="text" class="form-control" id="summary" name="summary" required />
						</div>
						<div class="form-group">
							<label for="image">图片</label><br>
    						<input type="file" id="image" name="image" />
						</div>
						<h5 id="image-invalid">请上传图像文件</h5>
						<img src="" alt="Image" class="img-fluid xy-img-post" id="preview-image" />
						<div class="form-group">
							<label for="content">内容</label>
							<textarea class="form-control" rows="15" id="content" name="content" required ></textarea>
						</div>
						<button type="submit" class="xy-btn">提交</button>
					</form>
				</section>
			</div>
		</div>
	</div>
</section>
{% else %}
<section class="xy-section">
	<div class="container-fluid">
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-8 col-lg-9 col-xl-9">
				<p>您还没登录，<a href="{% url 'blog:login' %}" class="xy-text-link">请先登录>>></a></p>
			</div>
			<aside class="col-xs-12 col-sm-12 col-md-4 col-lg-3 col-xl-3 xy-aside-r">
				<div class="xy-aside-container">
					<h3 class="xy-gold-text xy-title">可能想看</h3>
					<nav>
						<ul class="nav">
							<li><a href="#" class="xy-text-link">Lorem ipsum dolor sit</a></li>
							<li><a href="#" class="xy-text-link">Tincidunt non faucibus placerat</a></li>
							<li><a href="#" class="xy-text-link">Vestibulum tempor ac lectus</a></li>
							<li><a href="#" class="xy-text-link">Elementum egestas dui</a></li>
							<li><a href="#" class="xy-text-link">Nam in augue consectetur</a></li>
							<li><a href="#" class="xy-text-link">Fusce non turpis euismod</a></li>
							<li><a href="#" class="xy-text-link">Text Link Color #006699</a></li>
						</ul>
					</nav>
					<hr class="xy-margin-t-small">
				</div>
			</aside>
		</div>
	</div>
</section>
{% endif %}
{% endblock %}